import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/features/Providers";
import AppInitializer from "@/components/AppInitializer/AppInitilizer";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Parenting Assistant App - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${inter.variable} h-full antialiased`}>
      <Providers>
        <AppInitializer>
          <body className='min-h-full flex flex-col'>
            <Toaster />

            {children}
          </body>
        </AppInitializer>
      </Providers>
    </html>
  );
}
